[CHE-116] Update Default Sorts To Most Recent First
Code-Hammers/code-hammers pull request #114
Opened 2024-05-17 11:28 UTC by brok3turtl3

### Description

As part of the [CHE-110](https://codehammers.atlassian.net/browse/CHE-110?atlOrigin=eyJpIjoiOTMzYmQ5ODA0MTJlNDg4ZDlmY2RkYTQ4YWRiOWQyMmUiLCJwIjoiaiJ9) Forums Improvements story this PR adds sort methods to the database calls for threads and posts ensuring they display most recent entries at the top of the feed.

### Jira Task

[CHE-116](https://codehammers.atlassian.net/browse/CHE-116?atlOrigin=eyJpIjoiNGFkMzVjMTFlNTBmNDkyZWEwZTQxYzE5NjBmZTQ1MmIiLCJwIjoiaiJ9)

### Testing Instructions

1. Make sure branches are up to date and spin up dev server off feature branch.
2. Make sure entries are sorted in the expected order on All Forums, a specific forum, and inside a specific thread.

### Checklist

#### All Team Members

- [x] I added a descriptive title to this PR.
- [x] I filled out the **Description**, **Jira Task**, and **Testing Instructions** sections above.
- [ ] I added or updated [Jest unit tests]for any changes to components, server-side controllers, etc.
- [x] I ran `npm run docker-test` in my local environment to check that this PR passes all unit tests.
- [x] I did a quick check to make sure my code changes follow the recommended style guide.

### Additional Notes, Images, etc.

N/A

2024-05-18 03:15 UTC, JimmyTran48 requested changes

2024-05-18 03:15 UTC, JimmyTran48 commented on server/controllers/threadController.ts
Lots of receptive code. Can it be a separate middleware function in the chain?

2024-05-23 19:34 UTC, serenahromano approved these changes
it looks good to me but you can also make Jimmys changes if you want! but I'm good with keeping it like this

2024-05-23 20:11 UTC, seantokuzo approved these changes
This works for now but I 2nd what Jimmy says. Maybe a new ticket to refactor into some kind of reusable factory fx that handles the sorting and populating

2024-05-24 15:13 UTC, Mnelson98 approved these changes
Looks good, nice job!

2024-05-24 15:13 UTC, Mnelson98 commented on server/controllers/forumController.ts
> +      .populate("user", "firstName lastName");
Looks good.

2024-06-01 01:20 UTC, brok3turtl3 commented on server/controllers/threadController.ts
Im not sure if that would be worth it for these instances? BUT developing a piece of middleware that dynamically handles all sorts and filters sounds interesting.

2024-06-01 03:08 UTC, JimmyTran48 commented on server/controllers/threadController.ts
Not just sorting but the following logic is repeated multiple times. 

```
      .sort({ createdAt: -1 })
      .populate("user", "firstName lastName")
      .exec();
```

2024-06-01 03:08 UTC, JimmyTran48 approved these changes

2024-06-01 12:01 UTC, brok3turtl3 commented on server/controllers/threadController.ts
Yeah I figured that would get encapsulated in the sort helper. I pushed some new code up - This what you had in mind? I was curious about doing it so didn't bother making a ticket lol

2024-06-01 13:38 UTC, Mnelson98 approved these changes
Changes look good to me.

2024-06-01 16:46 UTC, JimmyTran48 commented on server/controllers/threadController.ts
Something like that, I was thinking more of middleware but a util function like you did is good! Would we need to declare the util function as an async function if we are `await`-ing it?

2024-06-01 17:17 UTC, brok3turtl3 commented on server/controllers/threadController.ts
I don't think so. Using the exec() method on the end of the query returns the promise directly so then the outer function can handle the `await` -ing part.

2024-06-01 21:16 UTC, JimmyTran48 approved these changes

2024-06-02 17:32 UTC, merged